apiharodoor/ApiHarodoor/Areas/HelpPage/Controllers/HelpController.cs
using System;
using System.Web.Http;
using System.Web.Mvc;
using ApiHarodoor.Areas.HelpPage.ModelDescriptions;
using ApiHarodoor.Areas.HelpPage.Models;

namespace ApiHarodoor.Areas.HelpPage.Controllers
{
    /// <summary>
    /// The controller that will handle requests for the help page.
    /// </summary>
    public class HelpController : Controller
    {
        private const string ErrorViewName = "Error";

        public HelpController()
            : this(GlobalConfiguration.Configuration)
        {
        }

        public HelpController(HttpConfiguration config)
        {
            Configuration = config;
        }

        public HttpConfiguration Configuration { get; private set; }

        public ActionResult Index()
        {
            ViewBag.DocumentationProvider = Configuration.Services.GetDocumentationProvider();
            return View(Configuration.Services.GetApiExplorer().ApiDescriptions);
        }

        public ActionResult Api(string apiId)
        {
            if (!String.IsNullOrEmpty(apiId))
            {
                HelpPageApiModel apiModel = Configuration.GetHelpPageApiModel(apiId);
                if (apiModel != null)
                {
                    return View(apiModel);
                }
            }

            return View(ErrorViewName);
        }

        public ActionResult ResourceModel(string modelName)
        {
            if (!String.IsNullOrEmpty(modelName))
            {
                ModelDescriptionGenerator modelDescriptionGenerator = Configuration.GetModelDescriptionGenerator();
                ModelDescription modelDescription;
                if (modelDescriptionGenerator.GeneratedModels.TryGetValue(modelName, out modelDescription))
                {
                    return View(modelDescription);
                }
            }

            return View(ErrorViewName);
        }
    }
}

apiharodoor/ApiHarodoor/Controllers/MPController.cs
using ClsModHarodoor.Common;
using ClsModHarodoor.MercadoPago;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection.Emit;
using System.Web;
using System.Web.Mvc;

namespace ApiHarodoor.Controllers
{
    public class MPController : Controller
    {
        // GET: MP
        public ActionResult Index(int PKUsuario,int Total)
        {
            ViewBag.Total = Total;
            ViewBag.TokenMercadoPago = "APP_USR-f32a39d9-ad0d-4737-a724-893ea3d9741a";
            ViewBag.PKUsuario = PKUsuario;
            return View();
        }


        [HttpPost]
        public JsonResult GenerarPago(ClsModParametrosMP Parametros)
        {
            MercadoPagoController Pagos = new MercadoPagoController();
            ClsModResponse objModResponse = new ClsModResponse();


            try
            {
                objModResponse = Pagos.CrearPago(Parametros);
                return Json(true);
            }
            catch
            {
                return Json(false);
            }
        }


    }
}

apiharodoor/ApiHarodoor/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    @*codigo para material design*@
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-material-design@4.1.1/dist/css/bootstrap-material-design.min.css" integrity="sha384-wXznGJNEXNG1NFsbm0ugrLFMQPWswR3lds2VeinahP8N0zJw9VWSopbjv2x7WCvX" crossorigin="anonymous">
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <link type="text/css" rel="stylesheet" href="css/materialize.min.css" media="screen,projection" />
</head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<body>

    <nav class="navbar fixed-top" style="background-color: #FF8225;">
        <h3 style="color:white;"><b>HD-ACCESS</b></h3>
    </nav>






    @*<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>

        </button>*@


    @*@Html.ActionLink("HD-ACCESS", "Index", "MP", new { area = "" }, new { @class = "navbar-brand" })*@

    @*<div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, null)</li>
                <li>@Html.ActionLink("API", "Index", "Help", new { area = "" }, null)</li>
            </ul>
        </div>*@

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - HD-ACCESS</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)


</body>
</html>